export interface ServiceContent {
  slug: string;
  h2: string;
  body: string[];
  sidebarHeading: string;
  problems: string[];
  processHeading: string;
  processSteps: [string, string, string][];
  costHeading: string;
  costBody: string[];
  faqs: [string, string][];
  ctaTitle: string;
  ctaText: string;
  testimonial: { quote: string; author: string; suburb: string };
  related: string[];
  image: string;
}

export const serviceContent: Record<string, ServiceContent> = {
  'emergency-plumbing': {
    slug: 'emergency-plumbing',
    h2: 'When water is moving through your home, minutes matter.',
    body: [
      'A burst pipe does not wait for business hours. Neither do we. Turquoise Plumbing provides genuine 24/7 emergency response across the Illawarra, from Shellharbour to Wollongong and every suburb in between. When you call, you speak to a real person who can talk you through the immediate steps while a plumber is on the way.',
      'The most common emergencies we attend are burst flexi hoses under sinks and behind washing machines. These thin braided connectors fail with age, and when they let go they can dump hundreds of litres of water into a home in minutes. If you can hear water running and cannot see the source, head straight to the water meter and shut it off. The meter is usually at the front boundary, under a metal or plastic lid. Turn the handle clockwise until it stops. That single step can be the difference between a mop-up and a major insurance claim.',
      'Not every urgent problem is an emergency. A slow drip from a tap is annoying but can wait until morning. What qualifies is anything that puts your home, your safety or your health at risk: water pouring from a ceiling or wall, a toilet overflowing with sewage, a gas smell inside the home, or a sudden total loss of hot water in the middle of winter. Storm-related flooding and overflowing gutters during heavy rain also count, especially if water is backing up into laundries or bathrooms.',
      'While you wait for us to arrive, there are a few things that help and a few that make things worse. Do turn off the water at the meter if a pipe has burst. Do turn off the gas at the meter if you smell gas and open windows. Do not try to dismantle a fitting or tighten a joint that is already leaking, since that often turns a small leak into a large one. Do not use electrical switches or appliances near standing water. If sewage is overflowing, keep everyone away from the area and do not attempt to clear the blockage yourself.',
    ],
    sidebarHeading: 'Signs you need a plumber right now.',
    problems: [
      'Water pouring from a ceiling, wall or under a cabinet',
      'A burst flexi hose behind a washing machine or sink',
      'Sewage overflowing from a drain or toilet',
      'No hot water and the system is leaking or making loud noises',
      'A gas smell inside the home or near an appliance',
      'Storm water backing up into the laundry or bathroom',
    ],
    processHeading: 'What happens when you call.',
    processSteps: [
      ['01', 'We talk you through it', 'On the phone we help you find and turn off the water or gas meter, so the damage stops while we are on the way.'],
      ['02', 'We prioritise the call', 'Emergencies go to the front of the queue. We give you an honest ETA based on where the plumber is and what traffic is doing.'],
      ['03', 'We stop the cause', 'On arrival we isolate the source, contain any water and make the area safe before any repair work begins.'],
      ['04', 'We fix and document', 'The repair is completed and tested. We photograph the damage and provide a report you can use for an insurance claim if needed.'],
    ],
    costHeading: 'What changes the cost of an emergency call.',
    costBody: [
      'After-hours and weekend calls carry a higher call-out rate, and we will tell you that rate before we dispatch. The total cost then depends on how long the repair takes, what parts are needed and how difficult the access is. A burst flexi hose behind a washing machine is usually a quick fix. A burst pipe inside a wall or under a slab takes longer and costs more.',
      'We always explain the call-out fee and the likely repair cost before starting work. If the job turns out to be simpler than expected, you pay for what was actually needed, not a padded estimate.',
    ],
    faqs: [
      ['What actually counts as a plumbing emergency?', 'Anything that is actively damaging your home or putting your safety at risk. Burst pipes, sewage overflow, gas leaks and sudden loss of hot water in cold weather all qualify. A dripping tap or a slow drain can wait.'],
      ['How do I turn off my water meter?', 'The meter is usually at your front boundary under a lid. Lift the lid, find the lever or handle on the pipe and turn it clockwise until it stops. If it is stiff, use a spanner or pliers but be careful not to force it.'],
      ['Do you charge a call-out fee after midnight?', 'Yes, after-hours calls carry a higher call-out rate. We tell you the rate on the phone before we dispatch so there is no surprise on the invoice.'],
      ['Will my insurance cover an emergency plumbing repair?', 'Many home insurance policies cover sudden water damage from burst pipes, but not gradual leaks or lack of maintenance. We provide a report with photos that you can submit with your claim. Check your policy or ask your insurer.'],
      ['What should I do if I smell gas?', 'Turn off the gas at the meter, open windows and doors, do not use any electrical switches or flames, leave the house and call us. If the smell is strong or you feel unwell, call 000 first.'],
    ],
    ctaTitle: 'Water where it should not be? We can be there today.',
    ctaText: 'Call now and we will talk you through the immediate steps while a plumber heads your way.',
    testimonial: { quote: 'A flexi hose burst behind our washing machine at 11pm. They talked us through turning the water off on the phone and were at the door in 25 minutes.', author: 'Homeowner', suburb: 'Warilla' },
    related: ['hot-water', 'gas-fitting', 'leak-detection', 'general-maintenance'],
    image: 'https://images.pexels.com/photos/18274115/pexels-photo-18274115.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'residential-plumbing': {
    slug: 'residential-plumbing',
    h2: 'Every home has its own plumbing story. We learn it before we touch it.',
    body: [
      'Residential plumbing is the broad overview of how water and waste move through your home. It covers everything from the meter at the front boundary to the waste pipe at the back of the property, and every tap, valve and fixture in between. Turquoise Plumbing works on homes across the Illawarra, from weatherboard cottages in Wollongong to brick veneer houses in Shellharbour and newer builds in Flinders and Shell Cove.',
      'The age and style of local housing stock tells us a lot about what to expect. Homes built before the 1970s often have galvanised or old copper supply pipes that narrow with internal build-up over decades. Post-war brick homes in Dapto and Port Kembla frequently have clay or earthenware sewer lines that crack and invite tree roots. Newer estates in Flinders and Shell Cove have PVC pipework but can still suffer from poor installation or shifting ground. Knowing the era of your home helps us diagnose faster and recommend the right fix rather than guessing.',
      'A common question from homeowners is whether to repair or replace. A tap that keeps dripping might need a new cartridge, or it might be a sign that your water pressure is too high and is wearing out every fixture in the house. A hot water system that has lasted twelve years is probably closer to the end than the middle of its life. We give you the honest answer: if a repair will last, we will do it. If replacement is the better investment, we will say so and explain why.',
      'Working around families and pets is part of the job. We keep work areas contained, clean up as we go and communicate about anything that might affect your household, like turning the water off for an hour or needing access to a bedroom to reach a pipe in the wall. A typical residential job starts with a phone call where we ask enough questions to understand the problem, followed by a visit where we diagnose, explain and quote before any non-urgent work begins. You are never left wondering what is happening or why.',
    ],
    sidebarHeading: 'When to call us about your home.',
    problems: [
      'Recurring leaks that keep coming back after a fix',
      'Low water pressure across multiple taps',
      'Noisy pipes, banging or vibrating when taps are used',
      'A hot water system that is past its expected lifespan',
      'Planning a renovation and need the plumbing assessed first',
      'Buying or selling a home and want a plumbing check',
    ],
    processHeading: 'How a typical home visit works.',
    processSteps: [
      ['01', 'We ask the right questions', 'On the phone we gather enough detail to arrive prepared, including the age of the home and what you have noticed.'],
      ['02', 'We assess the whole system', 'On site we look beyond the immediate symptom. A dripping tap might point to high pressure; a slow drain might mean tree roots further down the line.'],
      ['03', 'We explain in plain English', 'You get a clear picture of what is wrong, what it takes to fix it and what it costs, with no obligation to proceed.'],
      ['04', 'We leave it clean and working', 'The repair is tested, the area is tidied and you know what to watch for going forward.'],
    ],
    costHeading: 'What shapes the price of a home plumbing job.',
    costBody: [
      'The cost of residential work depends on what we find when we arrive. A straightforward tap washer replacement is a short visit with a small parts cost. Replacing a section of old galvanised pipe behind a wall takes longer, needs more material and may require opening and patching the wall.',
      'We always quote before starting non-urgent work. For jobs that need investigation first, like a hidden leak or a recurring blockage, we explain the diagnostic step and its cost, then quote for the repair once we know what is actually wrong.',
    ],
    faqs: [
      ['How do I know if my old pipes need replacing?', 'If you have galvanised supply pipes and are seeing brown water, low pressure or frequent leaks, replacement is usually the right call. We can inspect and show you what we find before recommending anything.'],
      ['What is the most common plumbing issue in older Illawarra homes?', 'Tree root intrusion in clay sewer lines is the one we see most. Dapto, Port Kembla and Oak Flats have a lot of post-war housing with original earthenware drains that crack over time.'],
      ['Should I replace a hot water system before it fails?', 'If your system is over ten years old, making unusual noises or running out of hot water faster than it used to, replacement is usually cheaper than waiting for a failure that leaves you with no hot water and possible water damage.'],
      ['Can you check the plumbing before I buy a house?', 'Yes. A pre-purchase plumbing inspection looks at the condition of pipes, drains, hot water and fixtures so you know what you are buying into. We can run a CCTV drain camera through the sewer line as part of that.'],
      ['Do you work with property managers and landlords?', 'Yes. We provide ongoing maintenance for rental properties, including routine checks, emergency response and clear invoicing that works for property management software.'],
    ],
    ctaTitle: 'Need a plumber who actually understands your home?',
    ctaText: 'Tell us what is going on and we will help you figure out the right next step, whether it is a quick fix or a bigger plan.',
    testimonial: { quote: 'They took the time to explain why our taps kept dripping. Turns out the pressure was too high. Fixed the real problem, not just the symptom.', author: 'Homeowner', suburb: 'Shellharbour' },
    related: ['hot-water', 'blocked-drains', 'tap-fixture-installations', 'general-maintenance'],
    image: 'https://images.pexels.com/photos/6419128/pexels-photo-6419128.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'hot-water': {
    slug: 'hot-water',
    h2: 'No hot water this morning? Let us find out why.',
    body: [
      'Hot water systems are one of the most common reasons people call a plumber, and for good reason. Losing hot water is not just inconvenient, it disrupts the whole household. Turquoise Plumbing repairs and replaces electric, gas, heat pump and solar hot water systems across the Illawarra, and we can help you choose the right replacement when repair is no longer the sensible option.',
      'The four main types of system each suit different households. Electric storage tanks are the most common and the cheapest to install, but they cost more to run over time. Gas storage systems heat faster and are cheaper to run if you already have gas connected. Continuous flow, or instantaneous, gas units heat water on demand so you never run out, but they need good gas pressure and flow rates to work properly. Heat pumps are the most energy-efficient option for homes without gas, working like a reverse air conditioner to heat water using ambient air. Solar systems use roof collectors and a storage tank, with gas or electric boost for cloudy days, and they have the lowest running cost but the highest upfront price.',
      'Storage tank versus continuous flow is a choice that depends on your household size and usage pattern. A family of five that all shower in the morning will empty a small storage tank quickly. A couple living in an apartment might never notice the difference. We help you size the system to the household, because an undersized system is the most common reason people call us back.',
      'Warning signs that your system needs attention include rust-coloured or cloudy hot water, a relief valve that drips constantly, water temperature fluctuating between scalding and cold, and running out of hot water much sooner than you used to. Any of these can mean the tank is corroding internally, the thermostat or element is failing, or sediment has built up to the point where efficiency has dropped. Coastal corrosion is a real factor in Illawarra suburbs near the water. Shellharbour, Warilla and Kiama homes with outdoor units exposed to salt air see shorter lifespans from metal components, and we factor that in when advising repair versus replacement.',
      'Correct sizing for your household matters. A system that is too small leaves you with cold showers on busy mornings. One that is too large wastes energy heating water you never use. We calculate the right capacity based on the number of bathrooms, the number of people and your peak usage times. Tempering valve requirements are also important. In NSW, hot water must be tempered to a maximum of 50 degrees at the outlet in residential homes, and 45 degrees in schools and care facilities. These valves wear out and need checking or replacing as part of regular maintenance.',
    ],
    sidebarHeading: 'Warning signs from your hot water system.',
    problems: [
      'Hot water runs out much faster than it used to',
      'Rust-coloured or cloudy water from hot taps',
      'A relief valve that drips or runs constantly',
      'Temperature swings between scalding and cold',
      'Loud banging or rumbling from the tank',
      'A system that is more than ten years old',
    ],
    processHeading: 'How we diagnose a hot water problem.',
    processSteps: [
      ['01', 'We check the basics first', 'Isolating valves, power or gas supply, relief valve operation and the age of the unit tell us a lot before we open anything.'],
      ['02', 'We test the components', 'For electric systems we test the element and thermostat. For gas we check burner operation, ignition and flue. For heat pumps we check the compressor and refrigerant.'],
      ['03', 'We give you the repair or replace answer', 'If a $200 element will get you another two years, we will say so. If the tank is corroding and the system is twelve years old, replacement is the better investment.'],
      ['04', 'We size and install correctly', 'If replacement is needed, we help you choose the right type and capacity, install it to code and test the tempering valve before we leave.'],
    ],
    costHeading: 'What drives the cost of a hot water repair or replacement.',
    costBody: [
      'A repair like replacing an element or a relief valve is typically a short job with a modest parts cost. A full replacement depends on the system type, capacity, gas or electrical connection work and whether the existing pipework and valves can be reused or need upgrading.',
      'Heat pump and solar systems cost more upfront but save significantly on running costs. Gas continuous flow units sit in the middle. We give you a written quote that includes the unit, installation, valves, pipework adjustments and disposal of the old system, so the number you see is the number you pay.',
    ],
    faqs: [
      ['How long should a hot water system last?', 'Electric and gas storage tanks typically last 8 to 12 years. Continuous flow units can last 15 to 20 years. Heat pumps and solar tanks vary. Coastal areas with salt air tend to shorten the lifespan of outdoor metal components.'],
      ['Should I repair or replace my old hot water system?', 'If the tank itself is leaking or corroding, replacement is the only option. If a component like an element, thermostat or relief valve has failed and the tank is sound, a repair can extend the life by years. We tell you honestly which is the case.'],
      ['What size hot water system do I need for my family?', 'It depends on the number of people, bathrooms and peak usage times. A family of five usually needs a 250L storage tank or a properly sized continuous flow unit. We calculate this for you so you do not end up with cold showers on busy mornings.'],
      ['What is a tempering valve and why does it matter?', 'A tempering valve mixes cold water with hot water to deliver a safe maximum temperature at the tap. In NSW residential homes it must be set to 50 degrees. These valves wear out over time and should be checked or replaced as part of system maintenance.'],
      ['Does coastal salt air affect hot water systems in the Illawarra?', 'Yes. Suburbs close to the water like Shellharbour, Warilla and Kiama see faster corrosion on outdoor metal components. We factor this in when recommending system types and suggest enclosed or coated units where exposure is high.'],
    ],
    ctaTitle: 'No hot water this morning? We can help today.',
    ctaText: 'Call us or send a few details about your system and we will work out whether it is a quick repair or time for a replacement.',
    testimonial: { quote: 'Our hot water died on a Sunday morning. They came out, diagnosed a dead element and had us back in hot water by lunchtime. Honest about whether the system was worth fixing.', author: 'Homeowner', suburb: 'Warilla' },
    related: ['gas-fitting', 'emergency-plumbing', 'appliance-installations', 'general-maintenance'],
    image: 'https://images.pexels.com/photos/34938439/pexels-photo-34938439.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'gas-fitting': {
    slug: 'gas-fitting',
    h2: 'Licensed gas work is never a do-it-yourself job.',
    body: [
      'Gas fitting is regulated work for a reason. A gas leak or a poorly installed connection can have serious consequences, and the law requires it to be done by a licensed gas fitter. Turquoise Plumbing holds the proper gas fitting licence and we handle everything from connecting a new cooktop to running new gas lines and conducting pressure tests.',
      'In NSW, any gas work must be done by a licensed gas fitter and a gas compliance certificate must be issued when the work is complete. This certificate is your proof that the work was done to standard. If you sell the home, the certificate may be requested by the buyer or their solicitor. Work done without a licence has no certificate and can create problems with insurance, warranties and property sales. We issue a compliance certificate for every gas job we complete.',
      'We connect and certify cooktops, ovens, freestanding stoves, gas heaters, gas hot water units and outdoor BBQ points. Each appliance has specific requirements for gas pressure, ventilation and clearances. A cooktop needs the right bayonet or hard-piped connection and a gas isolation valve within reach. A gas heater needs proper flueing and ventilation. An outdoor BBQ point needs a correctly rated hose and regulator. We make sure every connection meets the Australian standard, not just the minimum to get it working.',
      'Gas leak detection and pressure testing is a service we provide when you suspect a leak or when a new connection has been made. We pressure test the line with air to confirm it holds pressure, then use a gas detector to check every joint and fitting. If you smell gas in your home, turn off the gas at the meter, open windows and doors, do not use any electrical switches or flames and leave the house. Call us or 000 from outside. The difference between natural gas and LPG matters too. Natural gas is piped through the street main and is lighter than air, so it rises. LPG comes from bottles and is heavier than air, so it pools in low areas. The detection approach and ventilation requirements differ between the two.',
      'Running new gas lines and adding gas points is something we do for renovations and appliance upgrades. If you are moving a kitchen and need the cooktop relocated, adding a gas heater in a living room, or running a line out to a patio for an outdoor kitchen, we size the pipe correctly for the gas load and distance, test the line and issue the compliance certificate. A gas line that is too narrow for the appliances on it will cause poor performance and can be unsafe.',
    ],
    sidebarHeading: 'When to call a licensed gas fitter.',
    problems: [
      'You can smell gas inside or near an appliance',
      'A new cooktop, oven or heater needs connecting',
      'An existing gas appliance will not light or stays lit poorly',
      'You are renovating and need a gas line moved or extended',
      'An outdoor BBQ or kitchen point needs installing',
      'A gas compliance certificate is needed for work already done',
    ],
    processHeading: 'How a gas fitting job works.',
    processSteps: [
      ['01', 'We confirm the gas type and load', 'Natural gas and LPG have different requirements. We check what is connected, what the appliance needs and whether the existing line can support it.'],
      ['02', 'We isolate and test', 'Before any new connection, we pressure test the line to confirm it is sound. No gas work starts without a confirmed safe line.'],
      ['03', 'We connect and certify', 'The appliance is connected to code, tested for leaks with a gas detector and commissioned properly. We issue the gas compliance certificate.'],
      ['04', 'We document everything', 'You receive the compliance certificate and a record of the work, which you keep for insurance, warranty and future property sale purposes.'],
    ],
    costHeading: 'What affects the cost of gas fitting work.',
    costBody: [
      'The cost depends on the appliance, the distance from the gas supply, whether new pipework is needed and the complexity of the connection. Connecting a new cooktop where a gas line already exists is a straightforward job. Running a new gas line across a house to an outdoor kitchen is a larger project with more pipe, fittings and testing.',
      'We provide a written quote that includes all materials, testing, the compliance certificate and our labour. Gas work is not something to price-shop on, but we make sure our pricing is fair and transparent.',
    ],
    faqs: [
      ['Do I need a compliance certificate for gas work in NSW?', 'Yes. Every gas fitting job in NSW must be done by a licensed gas fitter and a compliance certificate must be issued. We provide this for every job. Without it, your insurance may not cover gas-related damage and you can have issues when selling the property.'],
      ['What do I do if I smell gas?', 'Turn off the gas at the meter, open windows and doors, do not use any electrical switches or open flames, leave the house and call us. If the smell is strong or you feel unwell, call 000 first from outside the property.'],
      ['What is the difference between natural gas and LPG?', 'Natural gas is piped through street mains and is lighter than air, so it rises and disperses. LPG comes from bottles and is heavier than air, so it pools in low areas. The two require different regulators, burners and ventilation approaches.'],
      ['Can you connect an outdoor BBQ gas point?', 'Yes. We run a properly sized gas line to an outdoor bayonet or hard-piped point, fit the correct hose and regulator, pressure test the line and issue the compliance certificate. We make sure the line is rated for outdoor use and the connection is weatherproof.'],
      ['How do you test for a gas leak?', 'We pressure test the gas line with air to confirm it holds pressure over a set period, then use an electronic gas detector to check every joint and fitting. We also do a visual inspection of all exposed pipework and connections.'],
    ],
    ctaTitle: 'Need a licensed gas fitter today?',
    ctaText: 'From a new cooktop connection to a gas leak investigation, we do the work properly and issue the compliance certificate.',
    testimonial: { quote: 'We needed a gas cooktop connected after a kitchen renovation. They tested the line, connected it properly and left us with the compliance certificate. Very professional.', author: 'Homeowner', suburb: 'Shell Cove' },
    related: ['hot-water', 'appliance-installations', 'bathroom-renovations', 'emergency-plumbing'],
    image: 'https://images.pexels.com/photos/33904619/pexels-photo-33904619.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'bathroom-renovations': {
    slug: 'bathroom-renovations',
    h2: 'A bathroom renovation lives or dies on what is behind the tiles.',
    body: [
      'The plumbing behind a bathroom renovation is what determines whether the finished room works or just looks good. Turquoise Plumbing handles the rough-in, waterproofing interfaces, waste connections and final fit-off for bathroom renovations across the Illawarra, coordinating with builders, tilers and other trades to keep the project on schedule.',
      'A bathroom renovation has two distinct plumbing stages. The rough-in happens early, before the waterproofing and tiling. This is when we set the floor waste, the shower waste, the vanity waste and water points, the toilet pan collar and any bidet or bath connections. Every position has to be right, because once the slab is screeded and the tiles are on, moving a waste point means breaking concrete. The fit-off happens at the end, when we install the tapware, the shower head, the toilet cistern and pan, and connect the vanity. Getting the timing of these two stages right is what keeps a renovation on schedule.',
      'Waterproofing requirements are strict in NSW. The entire floor of a wet area must be waterproofed, and walls must be waterproofed to a minimum height behind showers and baths. The floor waste must be positioned so water falls toward it, with correct fall on the floor screed. We work with the waterproofer to make sure the waste flange is set at the right height for the membrane, because a waste that is too high or too low causes drainage problems for the life of the bathroom.',
      'Relocating toilets, showers and vanities is one of the most common requests in a renovation and one of the most involved. Moving a toilet means rerouting the sewer pipe, which has a minimum fall requirement and a maximum distance to the vent. Moving a shower can mean cutting into the slab to reposition the waste. Moving a vanity changes where the water and waste connections come through the wall. We tell you what is involved before you commit to a layout, so you can decide whether the cost of moving things is worth it.',
      'Coordinating with tilers and other trades is where delays usually happen. The plumber needs to be in before the waterproofer, and back for fit-off after the tiler has finished. We schedule around the build program and communicate with your tiler or builder so everyone knows when to expect us. Choosing tapware and mixers early also matters. The rough-in positions depend on the specific fixtures you choose, since wall-mounted, deck-mounted and floor-mounted tapware all need different pipework. We help you finalise the fixture list before the rough-in so there are no surprises at fit-off.',
    ],
    sidebarHeading: 'Where bathroom renovations go wrong.',
    problems: [
      'Waste points positioned incorrectly so water does not drain properly',
      'Waterproofing that does not meet the NSW standard',
      'Tapware chosen too late, meaning rough-in positions are wrong',
      'Plumber and tiler not coordinated, causing delays',
      'Toilet relocated without checking sewer fall and vent distance',
      'Floor waste set at the wrong height for the waterproofing membrane',
    ],
    processHeading: 'How we plan a bathroom renovation.',
    processSteps: [
      ['01', 'We review the plans and fixtures', 'Before any work starts we look at the design, confirm the fixture list and flag anything that will not work with the existing plumbing.'],
      ['02', 'We do the rough-in', 'Wastes, water points, pan collar and valve positions are set. We coordinate with the waterproofer on waste flange heights and the tiler on floor fall.'],
      ['03', 'We come back for fit-off', 'After waterproofing and tiling are complete, we install all fixtures, connect tapware and test every fitting for leaks.'],
      ['04', 'We test and sign off', 'Every tap, waste and connection is tested. We check the floor waste drains properly and the toilet seals correctly.'],
    ],
    costHeading: 'What changes the cost of bathroom plumbing.',
    costBody: [
      'The plumbing cost of a bathroom renovation depends on how much is moving. Keeping the existing layout and just replacing fixtures is the most affordable option. Moving the toilet, shower or vanity means rerouting waste and water pipes, which can involve cutting and patching concrete or walls.',
      'We quote from your plans and fixture schedule before work starts. The quote covers the rough-in, the fit-off and any coordination with other trades. If the design changes mid-project, we tell you the cost impact before proceeding.',
    ],
    faqs: [
      ['What are the NSW waterproofing requirements for a bathroom?', 'The entire bathroom floor must be waterproofed. Walls must be waterproofed to at least 1.8 metres in shower areas and 150mm above the bath rim. The floor waste must be set at the correct height for the membrane. We coordinate with your waterproofer to make sure this is done right.'],
      ['Can I move my toilet to a different wall?', 'Yes, but it depends on the sewer fall and the distance to the vent. Sewer pipes need a minimum fall to work properly, and there is a maximum distance a pipe can run without a vent. We check what is possible before you commit to the new layout.'],
      ['When does the plumber need to come during a renovation?', 'Twice. First for the rough-in, before waterproofing and tiling. Then for the fit-off, after tiling is complete. We coordinate with your builder and tiler so the timing works for everyone.'],
      ['Do I need to choose my tapware before the rough-in?', 'Yes. Wall-mounted, deck-mounted and floor-mounted tapware all need different pipework. If you choose after the rough-in, the positions may not match and the wall may need to be reopened. We help you finalise the fixture list early.'],
      ['What causes the most delays in a bathroom renovation?', 'Poor coordination between trades. If the plumber is not scheduled before the waterproofer, or the tiler finishes before the fit-off tapware has arrived, the project stalls. We communicate with your builder and tiler to keep things moving.'],
    ],
    ctaTitle: 'Planning a bathroom renovation? Start with the plumbing.',
    ctaText: 'We will review your plans, flag any issues and give you a clear quote before any work starts.',
    testimonial: { quote: 'They picked up a waste position issue in our plans before the tiler started. Would have been an expensive mistake. Great coordination with our builder.', author: 'Homeowner', suburb: 'Flinders' },
    related: ['renovation-plumbing', 'tap-fixture-installations', 'toilet-repairs', 'gas-fitting'],
    image: 'https://images.pexels.com/photos/10486085/pexels-photo-10486085.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'blocked-drains': {
    slug: 'blocked-drains',
    h2: 'A blocked drain is a message from deeper in the system. We find out what it is saying.',
    body: [
      'Blocked drains are one of the most common plumbing problems in the Illawarra, and the blockage you can see is often not the real problem. A slow kitchen sink might be grease build-up in the pipe under the floor. A toilet that gurgles when the washing machine drains might mean tree roots in the main sewer line. Turquoise Plumbing clears the blockage and then investigates the cause, so it does not come back next month.',
      'We use CCTV drain camera inspection to see exactly what is happening inside the pipe. The camera shows us the condition of the pipe wall, the location and nature of any blockage, and whether the pipe has cracked, collapsed or dropped. This takes the guesswork out of drain work. Instead of assuming a blockage is just grease and jetting it, we can see whether tree roots have broken through a joint and whether the pipe needs repair, not just clearing.',
      'Hydro jetting and the electric eel are two different approaches to clearing a drain. An electric eel is a rotating cable with a cutting head that punches through a blockage. It is effective for soft blockages and has been the standard tool for decades. Hydro jetting uses high-pressure water to blast the inside of the pipe clean, cutting through roots and washing away grease, fat and debris. For most blockages we use hydro jetting because it cleans the pipe wall rather than just punching a hole through the blockage, which means the drain stays clear longer.',
      'Tree root intrusion is very common in the older Illawarra suburbs. Dapto, Port Kembla, Oak Flats and Warilla have many post-war homes with original clay or earthenware sewer lines. These pipes crack over time, and roots find their way in through the joints looking for water and nutrients. Once roots are in, they grow and eventually block the pipe completely. Clearing them gets you flowing again, but if the pipe is cracked, the roots will return. That is when pipe relining becomes the better option.',
      'What actually causes blockages matters. Wet wipes are a major culprit, even ones labelled as flushable, because they do not break down in water the way toilet paper does. Fats and oils poured down the kitchen sink solidify in the pipe and build up over time. Hair in shower drains combines with soap scum to form dense blockages. And tree roots, as mentioned, are the cause in many older homes. A drain that keeps blocking usually means a damaged or collapsed pipe, not just a recurring build-up. We can tell the difference with a camera inspection.',
      'Pipe relining is an alternative to excavation. Instead of digging up a section of pipe, we insert a resin-coated liner into the existing pipe, inflate it and let it cure. The result is a new pipe inside the old one, with no joints for roots to enter. It is less disruptive and often less expensive than digging up a driveway or garden to replace a section of pipe. We can tell you whether relining is suitable for your situation after a camera inspection.',
      'Stormwater and sewer blockages are different systems and need different approaches. Sewer lines carry waste from toilets, sinks and bathrooms to the main sewer. Stormwater lines carry rainwater from roofs, gutters and surface drains to the street or a soakwell. Mixing them up is illegal and can cause contamination. We identify which system is blocked before we start work.',
    ],
    sidebarHeading: 'Signs your drain is more than just slow.',
    problems: [
      'Gurgling sounds from drains when water runs elsewhere',
      'Water pooling around floor wastes in the bathroom',
      'A toilet that blocks repeatedly after clearing',
      'Multiple slow drains at the same time',
      'Wet patches or green patches in the lawn over the sewer line',
      'A smell of sewer gas inside or near the home',
    ],
    processHeading: 'How we clear and diagnose a blocked drain.',
    processSteps: [
      ['01', 'We clear the immediate blockage', 'Using hydro jetting or an electric eel, we get water flowing again so the home is usable. This is the urgent first step.'],
      ['02', 'We run the camera', 'A CCTV drain camera inspection shows us the pipe condition, the blockage location and whether there is structural damage.'],
      ['03', 'We explain what we found', 'You see the camera footage and we explain whether this was a one-off blockage or a sign of a damaged pipe that will recur.'],
      ['04', 'We recommend the right fix', 'If the pipe is sound, you are done. If there is root intrusion or a crack, we explain your options from regular maintenance to pipe relining or replacement.'],
    ],
    costHeading: 'What determines the cost of drain clearing.',
    costBody: [
      'A straightforward blockage that clears quickly with hydro jetting is a shorter, less expensive job. A blockage that requires camera inspection, multiple clears or pipe relining costs more. The location of the access point and the length of the pipe also affect the time and equipment needed.',
      'We always clear the drain first and then quote for any further work like relining or repair. You are not committed to a large job just because you called about a blockage. We show you the camera footage and explain the options before any repair work starts.',
    ],
    faqs: [
      ['Will hydro jetting damage my pipes?', 'No. Hydro jetting is safe for sound pipes. If a pipe is already cracked or collapsed, we identify that with a camera first and would not jet a damaged line. The water pressure is directed down the pipe, not against the pipe wall.'],
      ['Why does my drain keep blocking after it has been cleared?', 'If a drain blocks repeatedly, it usually means the pipe is damaged. Tree roots entering through a crack, a collapsed section or a sag in the pipe will cause the same blockage to return. A camera inspection shows us whether that is the case.'],
      ['What is pipe relining and is it better than digging?', 'Pipe relining inserts a resin-coated liner inside the existing pipe, creating a new pipe with no joints for roots to enter. It avoids excavation, which is particularly valuable when the pipe runs under a driveway, garden or the house. It is often less expensive than digging and replacing.'],
      ['Are flushable wet wipes actually safe to flush?', 'No. Even wipes labelled as flushable do not break down in water the way toilet paper does. They are one of the most common causes of drain blockages we see. The only things that should go down a toilet are human waste and toilet paper.'],
      ['What is the difference between a stormwater and sewer blockage?', 'Sewer lines carry waste from sinks, toilets and bathrooms. Stormwater lines carry rainwater from roofs and surface drains. They are separate systems and it is illegal to connect them. We identify which system is blocked before starting work, since the approach and the regulations differ.'],
    ],
    ctaTitle: 'Blocked drain? We can be there today.',
    ctaText: 'We will clear it, camera it and tell you whether it is a one-off or a sign of something deeper.',
    testimonial: { quote: 'Our drain had been cleared three times by different plumbers. Turquoise put a camera down, found roots in a cracked joint and relined the section. No more blockages.', author: 'Homeowner', suburb: 'Dapto' },
    related: ['leak-detection', 'pipe-repairs', 'emergency-plumbing', 'general-maintenance'],
    image: 'https://images.pexels.com/photos/220612/pexels-photo-220612.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'renovation-plumbing': {
    slug: 'renovation-plumbing',
    h2: 'New builds, extensions and granny flats need plumbing that is planned from the plan, not the problem.',
    body: [
      'Renovation plumbing and new installations cover the full scope of work for new builds, extensions, granny flats and major renovations. This is different from a repair job because we are working from plans, staging around a build program and coordinating with builders from the start. Turquoise Plumbing handles the complete pipework installation from the main connection through to the final fixture fit-off.',
      'New builds and extensions start with the rough-in. This is the stage where we install all the water supply lines, waste pipes and gas lines before the walls and floors are closed up. The positions are determined by the plans and the fixture schedule, and they have to be right. A waste pipe in the wrong place means breaking concrete after the slab is poured. A gas line that is too small for the appliances means tearing open walls. We work from the plans, confirm the fixture list with the builder or owner, and set every position to suit.',
      'Staging around the build program is critical. On a new build, the plumber is in and out several times. First for the main water and sewer connections, then for the slab rough-in, then for the wall rough-in, then for fit-off after the fit-out is complete. On an extension or granny flat, the sequencing is similar but tighter because we are connecting to an existing home. We coordinate with the builder so each stage happens when it should, and we do not hold up the next trade.',
      'Relocating water and sewer points is common in renovations. Moving a kitchen to a new wall, adding a bathroom where there was not one, or converting a garage into a living area all require new connections. We assess what is feasible based on the existing pipework, the fall available for sewer lines and the distance to the main connection. Sometimes a pump is needed to move waste to a higher line. We tell you what is possible and what it costs before you commit to the design.',
      'Connecting to mains water and sewer involves working with the water authority and the local council. New connections need approval and inspection. We handle the pipework to the boundary and coordinate the authority connection. Working from plans means we can provide a quote based on the drawings and fixture schedule before construction starts, which helps with budgeting and financing. Inspections and sign-off are part of the process. Plumbing work on new builds and extensions needs to pass inspection at the rough-in stage and at completion. We make sure the work is ready for inspection and we are on site when the inspector comes.',
      'Coordinating with builders is the part that makes or breaks a renovation timeline. We turn up when we say we will, communicate about what we need from the builder before we start, and leave the site ready for the next trade. If the plans change during the build, we price the variation and get it approved before doing the extra work.',
    ],
    sidebarHeading: 'When to bring the plumber in.',
    problems: [
      'Planning a new build, extension or granny flat',
      'Adding a bathroom or kitchen where there was not one',
      'Relocating water or sewer points in a renovation',
      'Connecting a new dwelling to mains water and sewer',
      'Need a plumbing quote from plans for a build budget',
      'Rough-in or fit-off stage of a current renovation',
    ],
    processHeading: 'How a renovation plumbing job runs.',
    processSteps: [
      ['01', 'We quote from the plans', 'Before construction starts, we review the drawings and fixture schedule and provide a written quote for the full plumbing scope.'],
      ['02', 'We do the rough-in', 'Water, waste and gas lines are installed and tested before the walls and slab are closed up. We coordinate with the builder on timing.'],
      ['03', 'We pass inspection', 'The rough-in is inspected by the certifier or council. We make sure everything is ready and are on site for the inspection.'],
      ['04', 'We fit off and sign off', 'After the fit-out is complete, we install all fixtures, test every connection and provide the compliance documentation.'],
    ],
    costHeading: 'How renovation plumbing is priced.',
    costBody: [
      'Because we are working from plans, we can provide a fixed quote before construction starts. The price depends on the number of fixtures, the length of pipe runs, the distance to the main connections and whether any new mains connections are needed. A granny flat with one bathroom and a kitchenette is a different scope from a four-bedroom house with two bathrooms and a laundry.',
      'If the plans change during the build, we price the variation in writing before doing the extra work. You always know what the plumbing will cost before it happens.',
    ],
    faqs: [
      ['Can you give me a plumbing quote from my building plans?', 'Yes. We review the drawings, the fixture schedule and the site plan and provide a written quote for the full plumbing scope before construction starts. This helps with your build budget and financing.'],
      ['How many times does the plumber need to come during a build?', 'Typically three to four times. First for the main connections, then for the slab rough-in, then for the wall rough-in, and finally for the fit-off after the fit-out is complete. We coordinate with your builder on timing.'],
      ['Do you handle the connection to mains water and sewer?', 'Yes. We install the pipework to the boundary and coordinate with the water authority for the connection. New connections need approval and inspection, which we manage as part of the job.'],
      ['Can you move a sewer point for a kitchen renovation?', 'Yes, if the fall and distance allow it. Sewer pipes need a minimum fall to work properly and there is a maximum distance to a vent. We assess what is feasible and tell you the cost before you commit to the new layout.'],
      ['What happens if the plans change during the build?', 'We price any variation in writing before doing the extra work. You approve the cost first, so there are no surprises on the final invoice.'],
    ],
    ctaTitle: 'Building or renovating? Get the plumbing quoted first.',
    ctaText: 'We will review your plans and give you a clear quote before construction starts, so your build budget is accurate from day one.',
    testimonial: { quote: 'They quoted from our plans before we started building. The price held through the whole project and they turned up on time for every stage.', author: 'Homeowner', suburb: 'Albion Park' },
    related: ['bathroom-renovations', 'gas-fitting', 'tap-fixture-installations', 'appliance-installations'],
    image: 'https://images.pexels.com/photos/29274530/pexels-photo-29274530.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'leak-detection': {
    slug: 'leak-detection',
    h2: 'A jump in your water bill is usually the first sign of a hidden leak.',
    body: [
      'Hidden leaks are among the most damaging plumbing problems because they go unnoticed while water seeps into walls, floors and foundations. Turquoise Plumbing provides leak detection and pipe repair across the Illawarra, using acoustic and thermal equipment to find leaks without tearing open walls on a guess.',
      'The first sign of a hidden leak is usually a water bill that jumps without explanation. If your usage has not changed but the bill has gone up significantly, a leak is the most likely cause. You can test this yourself using the water meter. Turn off all taps and appliances in the house, then check the meter. If the dial is still moving, you have a leak somewhere between the meter and the house. Note the meter reading, wait an hour without using any water, and check again. Any change confirms a leak.',
      'Acoustic leak detection uses a sensitive ground microphone to listen for the sound of water escaping under pressure. The leak makes a distinct noise that changes depending on the pipe material, pressure and depth. We trace the sound to its loudest point, which is the leak location. Thermal leak detection uses an infrared camera to find temperature differences on walls, floors and ceilings. A hot water leak shows up as a warm patch. A cold water leak shows as a cool patch. Both methods let us pinpoint the leak before we cut anything open.',
      'Slab leaks under concrete are a particular challenge. When a pipe runs under a concrete slab and develops a leak, the water has nowhere to go except into the foundation. Signs include warm spots on the floor, cracks in the slab, damp carpet or a musty smell. We use acoustic detection to find the leak under the slab, then make a targeted cut to access and repair the pipe, rather than breaking up the whole floor.',
      'Pinhole leaks in older copper pipe are common in homes with aggressive water chemistry or high pressure. These tiny leaks can be hard to spot but cause significant damage over time. Tree root damage is another cause, where roots have grown into a pipe joint and cracked the pipe wall. Wall and ceiling stains are often the visible sign of a leak that has been running for weeks or months. We trace the source and repair the pipe, not just the stain.',
      'We provide reports for insurance claims. If a leak has caused damage to your home, your insurer will want evidence of the source and extent of the leak. We document our findings with photos, thermal images and a written report that you can submit with your claim. This can make the difference between a claim being accepted and being denied.',
    ],
    sidebarHeading: 'Signs of a leak you cannot see.',
    problems: [
      'A water bill that has jumped without explanation',
      'Damp or discoloured patches on walls or ceilings',
      'A warm spot on the floor that could indicate a slab leak',
      'A constantly running water meter with all taps off',
      'A musty smell with no obvious source',
      'Cracks in walls or foundations that appeared recently',
    ],
    processHeading: 'How we find and fix a hidden leak.',
    processSteps: [
      ['01', 'We confirm the leak', 'Using the water meter we confirm a leak is present and determine whether it is on the supply or waste side of the system.'],
      ['02', 'We locate it precisely', 'Acoustic and thermal detection equipment pinpoints the leak to within a small area, so we know exactly where to access.'],
      ['03', 'We make a targeted repair', 'We open only what is needed to reach the pipe, repair the leak and test the line under pressure to confirm it holds.'],
      ['04', 'We document and report', 'We photograph the leak and the damage, and provide a written report for your insurance claim if needed.'],
    ],
    costHeading: 'What influences the cost of leak detection and repair.',
    costBody: [
      'The cost has two parts. The detection work is charged as an investigation, since it takes time and specialised equipment to find a hidden leak. The repair cost depends on what we find, where the pipe is and how much access work is needed to reach it.',
      'We quote the repair after we have found the leak, so you know the full cost before we start fixing it. If the leak is under a slab or behind a tiled wall, the access and making-good will cost more than a leak under a kitchen sink.',
    ],
    faqs: [
      ['How can I test for a leak using my water meter?', 'Turn off all taps and appliances, then check the meter. If the dial is still moving, you have a leak. Note the reading, wait an hour without using any water, and check again. Any change confirms a leak between the meter and the house.'],
      ['What is acoustic leak detection?', 'We use a sensitive ground microphone to listen for the sound of water escaping under pressure. The leak makes a distinct noise that we trace to its loudest point. This lets us find the leak without guessing where to dig or cut.'],
      ['What is a slab leak and how do you fix it?', 'A slab leak is a pipe leak under a concrete slab foundation. Signs include warm floor spots, cracks and damp carpet. We use acoustic detection to pinpoint the leak, then make a targeted cut in the slab to access and repair the pipe, rather than breaking up the whole floor.'],
      ['Why do I have pinhole leaks in my copper pipes?', 'Pinhole leaks are common in older copper pipe with aggressive water chemistry or high water pressure. The inside of the pipe corrodes locally until a tiny hole forms. If you are getting repeated pinhole leaks, it usually means the pipe is reaching the end of its service life and replacement is the better option.'],
      ['Can you provide a report for my insurance claim?', 'Yes. We photograph the leak and the damage, record the thermal images and provide a written report documenting the source and extent of the leak. This evidence can be submitted with your insurance claim.'],
    ],
    ctaTitle: 'Water bill higher than it should be? Let us find out why.',
    ctaText: 'We will trace the leak, repair the pipe and provide a report for your insurer if needed.',
    testimonial: { quote: 'Our water bill doubled and we could not figure out why. They found a pinhole leak in a copper pipe under the slab and fixed it with one small cut in the floor.', author: 'Homeowner', suburb: 'Kiama' },
    related: ['blocked-drains', 'pipe-repairs', 'emergency-plumbing', 'general-maintenance'],
    image: 'https://images.pexels.com/photos/4406597/pexels-photo-4406597.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'tap-fixture-installations': {
    slug: 'tap-fixture-installations',
    h2: 'New tapware should look right and work properly. Both matter.',
    body: [
      'Tap, sink and fixture installation is one of the most visible plumbing upgrades you can make. It changes the look and feel of a kitchen or bathroom instantly. Turquoise Plumbing installs and replaces tapware, sinks, basins, shower rails and fixtures across the Illawarra, making sure the finish is clean and the connections are sound.',
      'Mixer taps and three-piece sets are the two main tapware styles. A mixer uses a single lever or handle to blend hot and cold water through one spout. A three-piece set has separate hot and cold taps with a shared spout. Mixers are more common in modern homes because they are easier to use, allow precise temperature control and have a cleaner look. Three-piece sets suit period homes and heritage bathrooms. The choice affects the rough-in, since a mixer needs a single hole in the basin or sink while a three-piece set needs three holes with specific spacing.',
      'Ceramic cartridges have largely replaced traditional tap washers in modern tapware. A ceramic disc cartridge uses two polished ceramic plates that slide against each other to control water flow and temperature. They last longer than rubber washers, do not drip as they age and give a smoother feel. Traditional tap washers are still used in older homes and are cheaper to replace, but they wear out faster and drip more often. If you have taps that drip constantly, upgrading to ceramic cartridges is usually the better long-term fix.',
      'Kitchen sink and laundry tub installation involves more than just the sink. The waste, the overflow, the trap and the water connections all need to be correct. A kitchen sink replacement might need new waste fittings if the old ones do not match the new sink. A laundry tub might need a new trap if the existing one is the wrong size or height. We handle the full installation, not just bolting the sink in place.',
      'Outdoor taps and hose cocks are a simple but important addition. We install them with proper isolation valves so you can shut off the outdoor tap without turning off the house water, and with non-return valves to prevent contaminated water flowing back into the house supply. Shower rails and heads are another common upgrade. A new shower head can change the feel of a shower completely, but it needs to be compatible with the existing water pressure and flow rate.',
      'WELS water ratings are worth understanding. WELS stands for the Water Efficiency Labelling and Standards scheme. A tap or shower head with a higher WELS star rating uses less water per minute. A 6-star kitchen mixer can use as little as 4 litres per minute, compared to an older tap that might use 15 litres or more. Over a year, that is a significant saving on water bills. Matching finishes across a room is a detail that matters. Chrome, brushed nickel, matte black and gunmetal all look different under the same lighting. We help you coordinate finishes so the room looks intentional, not mixed.',
      'A dripping tap wastes more water than people expect. A tap that drips once per second wastes around 7,000 litres per year. That is not just an environmental concern, it is a real cost on your water bill. Fixing a dripping tap is usually a quick job, and it pays for itself in water savings.',
    ],
    sidebarHeading: 'When to upgrade your taps and fixtures.',
    problems: [
      'A tap that drips constantly or is stiff to turn',
      'A cracked or stained sink or basin that needs replacing',
      'A kitchen or bathroom refresh with new tapware',
      'An outdoor tap that needs adding or replacing',
      'A shower head with poor pressure or uneven spray',
      'Tapware finishes that do not match across the room',
    ],
    processHeading: 'How we install new fixtures.',
    processSteps: [
      ['01', 'We check compatibility', 'Before removing the old fixture, we confirm the new one matches the existing connections, hole spacing and water pressure.'],
      ['02', 'We isolate and remove', 'We shut off the water to the fixture, remove the old tap or sink and check the condition of the pipework behind it.'],
      ['03', 'We install and seal', 'The new fixture is fitted, sealed and connected. We use the correct sealants and fittings for the fixture type and surface.'],
      ['04', 'We test and adjust', 'We turn the water on, check for leaks at every connection and adjust the flow and temperature to make sure everything works as it should.'],
    ],
    costHeading: 'What affects the cost of a fixture installation.',
    costBody: [
      'A like-for-like tap replacement where the connections are sound is a short job. Replacing a sink that needs new waste fittings, different hole spacing or pipework adjustments takes longer. The fixture cost itself is separate from the installation, and we can supply and install or install a fixture you have already purchased.',
      'We quote before starting, and if we find the existing pipework needs more work than expected, we explain the additional cost before proceeding.',
    ],
    faqs: [
      ['What is the difference between a mixer tap and a three-piece set?', 'A mixer uses a single lever to blend hot and cold water through one spout and needs one hole. A three-piece set has separate hot and cold taps with a shared spout and needs three holes. Mixers suit modern homes, three-piece sets suit period homes. The choice affects the rough-in.'],
      ['Should I choose ceramic cartridges or traditional tap washers?', 'Ceramic cartridges last longer, drip less and feel smoother. Traditional washers are cheaper but wear out faster. If you are upgrading tapware, ceramic cartridges are the better long-term choice. If your current taps drip constantly, upgrading the cartridges usually fixes it for years.'],
      ['What does a WELS rating mean and does it save money?', 'WELS is the Water Efficiency Labelling and Standards scheme. A higher star rating means the tap or shower head uses less water per minute. A 6-star kitchen mixer can use as little as 4 litres per minute versus 15 litres for an old tap. Over a year, the water savings are significant on your bill.'],
      ['Can you install an outdoor tap with a separate shut-off valve?', 'Yes. We install outdoor taps with an isolation valve so you can turn off the outdoor tap without shutting off the house water. We also fit a non-return valve to prevent contaminated water flowing back into the house supply.'],
      ['How much water does a dripping tap actually waste?', 'A tap that drips once per second wastes around 7,000 litres per year. That is a real cost on your water bill, not just an annoyance. Fixing a dripping tap is usually a quick job and the savings pay for the repair.'],
    ],
    ctaTitle: 'New taps, a new sink, or a tap that just will not stop dripping?',
    ctaText: 'We will install it properly, match the finishes and make sure every connection is leak-free.',
    testimonial: { quote: 'We upgraded all the tapware in the house to matte black mixers. They matched the finishes across every room and the install was spotless. No leaks, no mess.', author: 'Homeowner', suburb: 'Shell Cove' },
    related: ['bathroom-renovations', 'appliance-installations', 'water-filters', 'general-maintenance'],
    image: 'https://images.pexels.com/photos/33686833/pexels-photo-33686833.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'appliance-installations': {
    slug: 'appliance-installations',
    h2: 'The delivery driver is not a plumber. Neither is the neighbour.',
    body: [
      'Water-connected appliances need proper plumbing connections, not just a hose pushed onto a tap. Turquoise Plumbing installs dishwashers, washing machines, plumbed fridges and other water-connected appliances across the Illawarra, making sure every connection is secure, every waste is correct and every isolation valve is in place.',
      'Dishwasher installation involves both a water supply and a waste connection. The water supply needs a dedicated isolation valve so the dishwasher can be shut off without turning off the kitchen water. The waste connection needs to be done correctly to prevent odour coming back up the line. We use a proper branch tail on the sink waste, not a clamp-on saddle that can leak or block. The water pressure needs to be within the dishwasher manufacturer specification, since too much pressure can damage the inlet valve.',
      'Washing machine taps and flexi hose replacement is one of the most important small jobs in a home. The flexi hoses that connect washing machines to the water supply are one of the most common causes of indoor flooding. They have a limited lifespan, typically 5 to 10 years, and they burst without warning. We replace old flexi hoses with new, rated hoses and fit isolation valves so the washing machine can be shut off independently. This is cheap insurance against a very expensive flood.',
      'Plumbed in fridges with ice and water dispensers need a dedicated water line run to the fridge location. This usually means a filtered water connection through the wall or under the floor, with an isolation valve accessible at the fridge. The water pressure needs to be regulated, since fridge ice makers are sensitive to high pressure. We run the line, fit the valve and connect the fridge, and we can also install the fridge water filter at the same time.',
      'Fitting isolation valves is a detail that saves a lot of trouble later. If every appliance has its own isolation valve, you can shut off the dishwasher, the washing machine or the fridge without turning off the water to the whole house. This matters when an appliance needs service or when a hose starts to leak. We fit isolation valves as standard on every appliance installation.',
      'Correct waste connections and air gaps prevent odour and backflow. A dishwasher waste that is connected incorrectly can let sewer gas into the kitchen. A washing machine waste that is too low can cause the machine to siphon. We install waste connections to code, with the correct fall and air gap where needed. An incorrect connection can void an appliance warranty or an insurance claim. If the manufacturer specifies a particular connection method and it is not done that way, the warranty may not cover water damage caused by a failure. We install to the manufacturer specification and document the work.',
    ],
    sidebarHeading: 'When to call us about an appliance.',
    problems: [
      'A new dishwasher that needs water and waste connections',
      'A washing machine flexi hose that is old or showing wear',
      'A new fridge with a water dispenser that needs plumbing',
      'An appliance with no isolation valve, so the whole house has to be shut off',
      'A waste connection that smells or is leaking',
      'An appliance installation that needs to meet warranty requirements',
    ],
    processHeading: 'How we install a water-connected appliance.',
    processSteps: [
      ['01', 'We check the existing connections', 'Before the appliance arrives, we check the water supply, the waste connection and whether an isolation valve is present. We flag anything that needs upgrading.'],
      ['02', 'We fit the isolation valve', 'Every appliance gets its own shut-off valve so it can be isolated without turning off the house water. This is standard on every install.'],
      ['03', 'We connect water and waste', 'The water supply is connected with a rated hose and the waste is connected to code, with the correct fall and air gap to prevent odour and backflow.'],
      ['04', 'We test and document', 'We run the appliance through a cycle, check every connection for leaks and document the installation to meet warranty requirements.'],
    ],
    costHeading: 'What changes the cost of an appliance installation.',
    costBody: [
      'A dishwasher installation where the water and waste are already in place is a straightforward job. Running a new water line to a fridge on the other side of the kitchen costs more. Replacing a flexi hose and fitting an isolation valve is a small but important job that we can often combine with other work.',
      'We quote before starting and explain what is included. If the existing connections need more work than expected, we tell you before proceeding.',
    ],
    faqs: [
      ['How often should washing machine flexi hoses be replaced?', 'Flexi hoses should be replaced every 5 to 10 years, regardless of whether they look fine. They degrade internally and burst without warning, and they are one of the most common causes of indoor flooding. We replace them with rated hoses and fit an isolation valve at the same time.'],
      ['Can you plumb in a fridge with a water dispenser?', 'Yes. We run a dedicated water line to the fridge location, fit an isolation valve accessible at the fridge, regulate the pressure to suit the ice maker and connect the fridge. We can also install or replace the fridge water filter at the same time.'],
      ['Why does my dishwasher waste connection smell?', 'It is usually because the waste was connected with a clamp-on saddle instead of a proper branch tail on the sink waste, or because there is no air gap to prevent sewer gas coming back up the line. We reconnect it to code with the correct fitting and air gap.'],
      ['Do I need an isolation valve for each appliance?', 'Yes. An isolation valve lets you shut off a single appliance without turning off the house water. This matters when an appliance needs service or a hose starts to leak. We fit them as standard on every appliance installation.'],
      ['Can an incorrect installation void my appliance warranty?', 'Yes. If the manufacturer specifies a particular connection method or pressure range and it is not done that way, the warranty may not cover water damage caused by a failure. We install to the manufacturer specification and document the work.'],
    ],
    ctaTitle: 'New appliance arriving? Let us connect it properly.',
    ctaText: 'We will fit the isolation valve, connect the water and waste to code and make sure the installation meets the warranty requirements.',
    testimonial: { quote: 'They replaced our old washing machine hoses and fitted isolation valves on both the washer and the dishwasher. Small job, big peace of mind.', author: 'Homeowner', suburb: 'Wollongong' },
    related: ['tap-fixture-installations', 'water-filters', 'gas-fitting', 'renovation-plumbing'],
    image: 'https://images.pexels.com/photos/3829555/pexels-photo-3829555.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'water-filters': {
    slug: 'water-filters',
    h2: 'Better tasting water starts with the right system, installed cleanly.',
    body: [
      'Water filtration is one of the most practical upgrades you can make to a kitchen. It removes the chlorine taste and odour from tap water, reduces sediment and provides clean, clear water for drinking and cooking without the cost and waste of bottled water. Turquoise Plumbing installs under-sink, whole-of-house and appliance water filtration systems across the Illawarra.',
      'Under-sink filtration and whole-of-house systems serve different purposes. An under-sink system filters water at a single tap, usually in the kitchen, and is the most common choice for drinking water. A whole-of-house system filters all the water entering the home, which means every tap, shower and appliance gets filtered water. Whole-of-house systems are larger, more expensive and are usually chosen when the mains water has sediment, iron or other issues that affect the whole home. For most households, an under-sink system is the practical choice.',
      'Reverse osmosis and carbon filtration work differently. A carbon filter uses activated carbon to absorb chlorine, chemicals and odours. It is simple, effective and affordable, and the cartridges are inexpensive to replace. Reverse osmosis forces water through a semi-permeable membrane that removes a much wider range of contaminants, including dissolved solids, heavy metals and fluoride. Reverse osmosis systems are more expensive, produce a slower flow rate and waste some water in the process, but they provide the purest filtered water. We help you choose based on what you actually need to remove from your water.',
      'What filtration removes depends on the system. Sediment filters catch sand, rust and particles. Carbon filters remove chlorine, taste and odour compounds. Reverse osmosis removes dissolved solids, heavy metals, fluoride, nitrates and more. If your concern is chlorine taste from the mains supply, a carbon filter is sufficient. If you are on tank water with sediment and bacterial concerns, a more comprehensive system is needed.',
      'Dedicated filter taps and three-way mixers are the two main delivery options. A dedicated filter tap is a separate small tap on the sink that dispenses only filtered water. A three-way mixer combines hot, cold and filtered water through a single spout, with a separate lever or button for filtered water. Three-way mixers are more popular in modern kitchens because they avoid a second tap on the sink, but they need a different rough-in. We help you choose and install both types.',
      'Cartridge replacement schedules matter. A carbon cartridge typically needs replacing every 6 to 12 months. A reverse osmosis membrane lasts 2 to 3 years, but the pre-filters need replacing more frequently. If cartridges are not changed, the filter stops working effectively and can actually degrade water quality by releasing trapped contaminants back into the water. We set up a replacement schedule and can send a reminder when it is due. Plumbed in fridge and ice maker filters are another common installation. We run a filtered water line to the fridge and fit the filter in an accessible location for easy replacement.',
      'Backflow prevention requirements are important for water filter installations. A water filter is a connection to the mains supply, and it needs backflow protection to prevent filtered water flowing back into the mains. We install the correct backflow prevention device as part of every filter installation, to meet the water authority requirements and protect the mains supply.',
    ],
    sidebarHeading: 'Choosing the right water filter.',
    problems: [
      'Chlorine taste and odour from the mains water supply',
      'Sediment or discolouration in the tap water',
      'An old filter system that needs replacing',
      'A fridge with a water dispenser that needs a filtered line',
      'A three-way mixer that combines hot, cold and filtered water',
      'Cartridges that have not been changed and the filter is no longer effective',
    ],
    processHeading: 'How we install a water filter system.',
    processSteps: [
      ['01', 'We assess your water and needs', 'We check what you want to remove from the water and recommend the right system type, from a simple carbon filter to a reverse osmosis unit.'],
      ['02', 'We plan the installation', 'We confirm the delivery method, whether a dedicated tap or a three-way mixer, and the location of the filter housing for easy cartridge access.'],
      ['03', 'We install and connect', 'The filter is installed under the sink or at the mains entry, connected with the correct isolation valve and backflow prevention device.'],
      ['04', 'We test and schedule', 'We flush the system, test the water flow at the filtered tap and set up a cartridge replacement schedule so the filter keeps working effectively.'],
    ],
    costHeading: 'What determines the cost of a water filter installation.',
    costBody: [
      'The cost depends on the system type, the delivery method and the installation location. A simple under-sink carbon filter with a dedicated tap is the most affordable option. A reverse osmosis system with a three-way mixer costs more. A whole-of-house system is the largest investment.',
      'We quote before starting and the price includes the system, the installation, the backflow prevention device and the initial cartridge set. Replacement cartridges are an ongoing cost that we can explain, and we set up a schedule so you know when to change them.',
    ],
    faqs: [
      ['How often do water filter cartridges need replacing?', 'Carbon cartridges typically need replacing every 6 to 12 months. Reverse osmosis membranes last 2 to 3 years, but the pre-filters need replacing more frequently. If cartridges are not changed, the filter stops working and can release trapped contaminants back into the water.'],
      ['What is the difference between reverse osmosis and carbon filtration?', 'Carbon filtration absorbs chlorine, chemicals and odours and is simple and affordable. Reverse osmosis forces water through a membrane that removes dissolved solids, heavy metals, fluoride and more. Reverse osmosis provides purer water but is slower and wastes some water in the process.'],
      ['Should I choose a dedicated filter tap or a three-way mixer?', 'A dedicated filter tap is a separate small tap on the sink. A three-way mixer combines hot, cold and filtered water through one spout. Three-way mixers are more popular in modern kitchens but need a different rough-in. We install both.'],
      ['Do I need backflow prevention for a water filter?', 'Yes. A water filter is a connection to the mains supply and needs backflow protection to prevent filtered water flowing back into the mains. We install the correct backflow prevention device as part of every filter installation to meet water authority requirements.'],
      ['Can you plumb a water filter to my fridge?', 'Yes. We run a filtered water line to the fridge, fit the filter in an accessible location for easy cartridge replacement and connect the fridge. We can also install or replace the fridge internal filter at the same time.'],
    ],
    ctaTitle: 'Want better tasting water at home?',
    ctaText: 'We will recommend the right system for your water and your kitchen, and install it cleanly with the correct backflow prevention.',
    testimonial: { quote: 'The chlorine taste was putting us off drinking tap water. They installed a three-way mixer with a carbon filter and the water tastes completely different now. Very neat install.', author: 'Homeowner', suburb: 'Kiama' },
    related: ['tap-fixture-installations', 'appliance-installations', 'bathroom-renovations', 'general-maintenance'],
    image: 'https://images.pexels.com/photos/6857798/pexels-photo-6857798.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'toilet-repairs': {
    slug: 'toilet-repairs',
    h2: 'A running toilet is not just annoying. It is pouring water down the drain.',
    body: [
      'Toilets are one of the most used fixtures in any home and one of the most common sources of plumbing problems. Turquoise Plumbing repairs and installs toilets across the Illawarra, from a running cistern to a full replacement with a new pan and concealed cistern.',
      'Running and leaking cisterns waste a surprising amount of water. A toilet that runs continuously can waste hundreds of litres per day, which shows up on your water bill. The most common cause is a worn flapper valve or flush valve seal that does not close properly. Water leaks from the cistern into the pan continuously. The inlet valve can also fail, causing the cistern to overfill and run into the overflow tube. We diagnose the specific cause and replace the worn part, rather than replacing the whole cistern.',
      'Cistern and inlet valve parts have a limited lifespan. The flapper valve, the inlet valve, the flush button and the overflow tube all wear out over time. Most modern cisterns use standard replacement parts, but older cisterns can have discontinued parts that need sourcing. We carry common parts on the van and can usually repair a cistern in a single visit.',
      'Flush button and flush valve failures are common. A flush button that sticks or does not return can cause the toilet to run continuously. A flush valve that does not seal closes incompletely, letting water leak into the pan. A weak or incomplete flush can mean the flush valve is not opening fully or the rim jets in the pan are blocked by mineral build-up. We clean and replace the affected components.',
      'Leaking at the base and pan collar replacement is a different problem. If water appears around the base of the toilet when you flush, the pan collar or the seal between the pan and the floor is failing. This can damage the floor and the subfloor if left. We remove the pan, replace the pan collar and reseal the connection. A wobbly pan is often a sign that the pan collar has failed or the fixing has come loose, and it should not be ignored.',
      'Back to wall and concealed cistern installations are common in renovations. A back to wall toilet sits flush against the wall with the cistern hidden behind a panel or inside the wall. These look clean and modern, but they need a specific rough-in and a access panel for maintenance. We install back to wall and concealed cistern toilets as part of renovations and as standalone upgrades, and we make sure the cistern is accessible for future servicing.',
      'WELS water ratings matter for toilets. A toilet with a 4-star WELS rating uses around 4.5 litres per full flush, compared to an older toilet that might use 11 litres. Replacing an old toilet with a high-efficiency model can save a family of four around 25,000 litres per year. How to tell the difference between a blocked toilet and a blocked sewer line: if one toilet is blocked but the others in the house are fine, it is likely a local toilet blockage. If multiple toilets or drains are slow or blocked, the problem is in the sewer line and needs a different approach. We can tell the difference and recommend the right fix.',
    ],
    sidebarHeading: 'What your toilet is telling you.',
    problems: [
      'A cistern that runs continuously after flushing',
      'A weak or incomplete flush that does not clear the pan',
      'Water appearing around the base of the toilet when flushing',
      'A flush button that sticks or does not return',
      'A wobbly or loose toilet pan',
      'An old toilet that uses far more water than necessary',
    ],
    processHeading: 'How we diagnose and fix a toilet problem.',
    processSteps: [
      ['01', 'We identify the fault', 'We check whether the problem is the inlet valve, the flush valve, the flapper seal, the pan collar or a blockage. Each has a different fix.'],
      ['02', 'We carry common parts', 'Most cistern repairs can be done with parts we carry on the van. We replace the worn component rather than the whole cistern where possible.'],
      ['03', 'We test the flush', 'After the repair we run several flushes to confirm the cistern fills and stops correctly, the flush is full and strong, and no water leaks at the base.'],
      ['04', 'We check the pan and seal', 'If the pan is wobbling or leaking at the base, we check the pan collar and the floor seal and replace them if needed to prevent floor damage.'],
    ],
    costHeading: 'What affects the cost of a toilet repair or replacement.',
    costBody: [
      'A cistern repair like replacing a flapper valve or an inlet valve is a quick job with a small parts cost. A full toilet replacement, including removing the old pan and cistern, installing the new one and resealing the floor, costs more. A concealed cistern installation in a renovation is a larger job that needs to be planned into the build.',
      'We quote before starting any replacement work. For repairs, we explain the likely cost on the phone and confirm before proceeding on site.',
    ],
    faqs: [
      ['Why does my toilet keep running after I flush?', 'The most common cause is a worn flapper valve or flush valve seal that does not close properly, letting water leak from the cistern into the pan. The inlet valve can also fail and cause the cistern to overfill. We replace the worn part rather than the whole cistern.'],
      ['How do I know if my toilet is leaking at the base?', 'If water appears around the base of the toilet when you flush, the pan collar or the seal between the pan and the floor is failing. This can damage the floor and subfloor if left. A wobbly pan is often a sign the pan collar has failed. We remove the pan, replace the collar and reseal.'],
      ['What is the difference between a blocked toilet and a blocked sewer line?', 'If one toilet is blocked but the others in the house are fine, it is likely a local blockage in that toilet. If multiple toilets or drains are slow or blocked at the same time, the problem is in the sewer line and needs a drain camera or hydro jetter, not just a plunger.'],
      ['How much water does a running toilet waste?', 'A toilet that runs continuously can waste hundreds of litres per day. Over a billing period, that adds significantly to your water bill. Fixing a running toilet is usually a quick repair and the savings on your bill often exceed the cost of the repair.'],
      ['What WELS rating should I look for in a new toilet?', 'A 4-star WELS rated toilet uses around 4.5 litres per full flush, compared to 11 litres for an older model. Replacing an old toilet with a high-efficiency model can save a family of four around 25,000 litres per year. We can recommend and install suitable models.'],
    ],
    ctaTitle: 'Toilet running, leaking or just not flushing properly?',
    ctaText: 'We will diagnose the fault, carry the common parts and fix it in a single visit in most cases.',
    testimonial: { quote: 'Our toilet had been running for weeks. They replaced the flapper valve in twenty minutes and the water bill dropped noticeably the next quarter.', author: 'Homeowner', suburb: 'Oak Flats' },
    related: ['bathroom-renovations', 'blocked-drains', 'tap-fixture-installations', 'general-maintenance'],
    image: 'https://images.pexels.com/photos/4239015/pexels-photo-4239015.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },

  'general-maintenance': {
    slug: 'general-maintenance',
    h2: 'The small jobs that stop the big ones. That is what this page is about.',
    body: [
      'General plumbing repairs and maintenance is the preventative side of plumbing. It is about catching the small problems before they become the expensive ones, keeping fixtures and pipework in good condition and making sure the systems in your home are not heading toward a failure. Turquoise Plumbing handles ongoing maintenance, small repairs and property manager work across the Illawarra.',
      'Annual plumbing checks are the starting point. Just like a car service, a yearly check of the plumbing in a home catches things early. We check tap washers and cartridges for wear, inspect flexi hoses for signs of degradation, test the water pressure, check the relief valve on the hot water system, look at the condition of visible pipework and run water through all the drains to check for slow flow. A check like this takes an hour or two and can prevent a burst hose or a failed valve that causes thousands in damage.',
      'Replacing flexi hoses before they burst is one of the most valuable maintenance tasks we do. Flexi hoses are the braided connectors under sinks and behind washing machines, and they are one of the most common causes of household water damage claims in Australia. They have a limited lifespan and they fail without warning. We replace flexi hoses proactively, typically every 5 to 10 years, and we fit isolation valves at the same time so each fixture can be shut off independently. This is cheap insurance against a very common and very expensive problem.',
      'Checking and regulating water pressure is another important maintenance step. High water pressure feels good in the shower but it damages fixtures and appliances over time. It wears out tap washers and cartridges, puts stress on flexi hoses and pipe joints, and can reduce the lifespan of dishwashers, washing machines and hot water systems. We test the pressure and install a pressure limiting valve if it is too high. The ideal residential water pressure is between 450 and 500 kPa.',
      'Tap washers and cartridges are the most common small repair. A dripping tap is usually a worn washer or a failed cartridge, and it is a quick fix. But if multiple taps are dripping, it often points to high water pressure rather than individual wear. We look at the cause, not just the symptom. Gutters, downpipes and stormwater are part of the plumbing system too. Blocked gutters and downpipes cause water to overflow near the foundations, which can lead to damp and structural issues. We clear and check stormwater systems, particularly before the wetter months.',
      'Maintenance for landlords and property managers is a service we provide regularly. Rental properties need ongoing plumbing attention to keep them safe and functional for tenants. We handle routine maintenance, emergency response and end-of-tenancy repairs, with clear invoicing that works for property management software. We communicate with the property manager and the tenant, and we document the work for the owner.',
    ],
    sidebarHeading: 'What a maintenance visit covers.',
    problems: [
      'A list of small plumbing jobs that has been building up',
      'Flexi hoses that are old and have not been replaced',
      'High water pressure that is wearing out fixtures',
      'Tap washers and cartridges that keep failing',
      'Gutters and downpipes that need clearing before wet season',
      'A rental property that needs ongoing plumbing maintenance',
    ],
    processHeading: 'How a maintenance visit works.',
    processSteps: [
      ['01', 'We work through your list', 'Bring us every small plumbing job in one visit and we work through them efficiently, which is more cost-effective than separate call-outs.'],
      ['02', 'We do a preventative check', 'While we are there we check the flexi hoses, test the water pressure, inspect the relief valve and look at the condition of visible pipework.'],
      ['03', 'We flag what needs attention', 'We tell you what is fine, what should be done soon and what is urgent, so you can prioritise and budget.'],
      ['04', 'We document for your records', 'We provide a record of the work done and any recommendations, which is useful for property managers and owners.'],
    ],
    costHeading: 'How maintenance plumbing is priced.',
    costBody: [
      'Maintenance work is charged based on the time and parts required. Grouping small jobs into one visit is more cost-effective than separate call-outs, since you pay one call-out fee and one block of labour. We can provide a fixed price for specific tasks or an hourly rate for a general maintenance visit.',
      'For landlords and property managers, we provide clear invoicing with a breakdown of work done, parts used and recommendations for future attention. We can work within a maintenance budget and flag anything that needs to be escalated to the owner.',
    ],
    faqs: [
      ['How often should flexi hoses be replaced?', 'Flexi hoses should be replaced every 5 to 10 years, regardless of how they look. They degrade internally and burst without warning, and they are one of the most common causes of household water damage claims in Australia. We replace them proactively and fit isolation valves at the same time.'],
      ['What water pressure is too high for a home?', 'Anything above 500 kPa is considered high for a residential home. High pressure wears out tap washers, cartridges, flexi hoses and appliances faster. We test the pressure and install a pressure limiting valve if needed. The ideal range is 450 to 500 kPa.'],
      ['Why do my tap washers keep wearing out?', 'If you are replacing tap washers frequently, the cause is usually high water pressure rather than the quality of the washers. High pressure wears out washers and cartridges faster than normal. We test the pressure and install a limiting valve, which stops the recurring wear.'],
      ['Do you provide maintenance for rental properties?', 'Yes. We handle routine maintenance, emergency response and end-of-tenancy repairs for rental properties. We communicate with the property manager and the tenant, provide clear invoicing for property management software and document the work for the owner.'],
      ['Can I group multiple small jobs into one visit?', 'Yes, and it is more cost-effective to do so. You pay one call-out fee and one block of labour instead of multiple separate visits. Bring us every small plumbing job at once and we will work through the list efficiently.'],
    ],
    ctaTitle: 'Got a list of small plumbing jobs? Bring them all to us at once.',
    ctaText: 'We will work through the list, do a preventative check and flag anything that needs attention before it becomes a bigger repair.',
    testimonial: { quote: 'We had a list of five small jobs that had been building up for months. They knocked them all off in one visit and replaced two flexi hoses while they were here. Very efficient.', author: 'Homeowner', suburb: 'Port Kembla' },
    related: ['residential-plumbing', 'leak-detection', 'tap-fixture-installations', 'emergency-plumbing'],
    image: 'https://images.pexels.com/photos/16509869/pexels-photo-16509869.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
};
